package ru.project.entity.enums;

public enum UserState {
    BASIC_STATE,
    WAIT_FOR_EMAIL_STATE,
    WAIT_FOR_NAME_STATE,
    WAIT_FOR_QUANTITY_STATE,
    WAIT_FOR_DATE_STATE,
    WAIT_FOR_INFO_STATE,
    WAIT_FOR_NAME_TO_DELETE_STATE,
    WAIT_FOR_NAME_TO_TAKE_STATE,
    WAIT_FOR_SHOW_STATE
}
